### ISSUE TITLE
Missing lib pthread

### ISSUE THREAD

**Issue by szepeviktor** [frachop/hubic-backup#10]
Had to add `-lpthread` to `LIBS` in both makefiles on jessie.

**Comment by szepeviktor** [comment]
@frachop I hope I am not wrong on this.

**Comment by frachop** [comment]
I understand the pthread lib is missing. I will add it to LIBS.
btw, what is Jessie ?

**Comment by szepeviktor** [comment]
Is a Debian release
https://www.debian.org/releases/stable/

**Comment by frachop** [comment]
Ok, great.
I commited with pthread lib linking.
Thanks
