### ISSUE TITLE
Mac OSX jsoncpp header file are located in <json/json.h>

### ISSUE THREAD

**Issue by vmalguy** [frachop/hubic-backup#14]
On Mac OS X 10.10 with libjsoncpp install through "brew",  jsoncpp header file is located at  /usr/local/include/json/json.h not  /usr/local/include/**_jsoncpp_**/json/json.h 

So you will need to change all reference to jsoncpp/json/json.h to json/json.h in the project to compile it.

Errors references : 

```
./common.h:54:10: fatal error: 'jsoncpp/json/json.h' file not found
#include <jsoncpp/json/json.h>
checking jsoncpp/json/json.h usability... no
checking jsoncpp/json/json.h presence... no
checking for jsoncpp/json/json.h... no
configure: error: Can't find jsoncpp headers
```

**Comment by frachop** [comment]
I remove the jsoncpp dependency.
instead, i use [jsonxx](https://github.com/hjiang/jsonxx) which is embedded in thirdparty folder.
So this fix your problem

**Comment by vandyckruben** [comment]
Cannot build the software anymore on Ubuntu, maybe because of the change you made in json dependency?

> /hubic-backup/src/credentials.cpp:66: undefined reference to `jsonxx::Object::Object()'
> /hubic-backup/src/credentials.cpp:67: undefined reference to`jsonxx::Object::parse(std::string const&)'
> /hubic-backup/src/credentials.cpp:90: undefined reference to `jsonxx::Object::~Object()'
> /hubic-backup/src/credentials.cpp:90: undefined reference to`jsonxx::Object::~Object()'
> credentials.o: In function `std::string& jsonxx::Object::get<std::string>(std::string const&)':
> /hubic-backup/src/../thirdparty/jsonxx/jsonxx.h:368: undefined reference to`jsonxx::assertion(char const_, int, char const_, bool)'
> credentials.o: In function `get<std::basic_string<char> >':
> /hubic-backup/src/../thirdparty/jsonxx/jsonxx.h:440: undefined reference to`jsonxx::assertion(char const_, int, char const_, bool)'
> token.o: In function `CToken::fromJson(std::string const&)':
> /hubic-backup/src/token.cpp:34: undefined reference to`Json::Value::Value(Json::ValueType)'
> /hubic-backup/src/token.cpp:35: undefined reference to `Json::Reader::Reader()'
> /hubic-backup/src/token.cpp:36: undefined reference to`Json::Reader::parse(std::string const&, Json::Value&, bool)'
> /hubic-backup/src/token.cpp:38: undefined reference to `Json::Reader::getFormatedErrorMessages() const'
> /hubic-backup/src/token.cpp:57: undefined reference to`Json::Value::~Value()'
> /hubic-backup/src/token.cpp:53: undefined reference to `Json::Value::operator[](char const*)'
> /hubic-backup/src/token.cpp:53: undefined reference to`Json::Value::asString() const'
> /hubic-backup/src/token.cpp:54: undefined reference to `Json::Value::operator[](char const*)'
> /hubic-backup/src/token.cpp:54: undefined reference to`Json::Value::asString() const'
> /hubic-backup/src/token.cpp:55: undefined reference to `Json::Value::operator[](char const*)'
> /hubic-backup/src/token.cpp:55: undefined reference to`Json::Value::asInt() const'
> /hubic-backup/src/token.cpp:56: undefined reference to `Json::Value::operator[](char const*)'
> /hubic-backup/src/token.cpp:56: undefined reference to`Json::Value::asString() const'
> /hubic-backup/src/token.cpp:47: undefined reference to `Json::Value::isMember(std::string const&) const'
> /hubic-backup/src/token.cpp:57: undefined reference to`Json::Value::~Value()'

**Comment by frachop** [comment]
You're right !
I know where the problem comes from.
I'm on it.

**Comment by frachop** [comment]
Fixed.
Thanks for this report.

**Comment by frachop** [comment]
Fixed. Thank for your report.
