### ISSUE TITLE
Not working from bash script

### ISSUE THREAD

**Issue by stylersnico** [frachop/hubic-backup#15]
Hi,

The command line works from CLI but not from a bash script.
Nothing is show in the log file.

Any idea why?

Thanks

**Comment by frachop** [comment]
Hi,

Could you paste the script part ?
what are the hubic-backup arguments ?
What is the log level ?

**Comment by stylersnico** [comment]
Hi,

I've found a workaround.
I just need to put /usr/local/bin/hubic-backup in place of hubic-backup

**Comment by frachop** [comment]
Ok.
