### ISSUE TITLE
Increase amount of threads?

### ISSUE THREAD

**Issue by peixotorms** [frachop/hubic-backup#19]
Hi, uploading is so slow that I was wondering if we can increase the upload threads to something like 16 out of the current 4?

**Comment by frachop** [comment]
Hi, i'm not sure increasing the upload thread count will change the transfert speed unless you backup many small files.
I add this to the next feature list.

**Comment by wsw70** [comment]
From the source code, it looks like the threads are computed based on the number of cores. On my 4 cores machine this is one thread.
The upload is horribly slow (an average of 2-3 KB/sec) on a 250 Mbps uplink in France, with an insignifiant usage of RAM / CPU.

**Comment by frachop** [comment]
I'm in France too with a 250Mbps link too and when i backup my sources repository (thousands of small text files) it is indeed horribly slow. I tried with 5/10/20/50/150 thread and the gain is really not very significant.
with 150 uploading threads, i get a 150KB/s upload bandwith ... that is approximatly 15-20 file per seconds which is horribly slow compare to 250Mbps ...
But you're right, i will add this feature next so we could tweak this value if we backup big or small files.

**Comment by extremeshok** [comment]
Quickest is still to tar the small files and then upload them as a large
single file.

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by frachop** [comment]
Hi,

I add the `--up-thread-count` option, so you can test.
