### ISSUE TITLE
Backup files deleted locally still on the cloud

### ISSUE THREAD

**Issue by frachop** [frachop/hubic-backup#5]
When you delete a local file which had already been backuped, the cloud file still exists and was not deleted.

step 1.
backup a folder which contains 2 files : a.txt and b.txt

step 2.
delete locale file a.txt

step 3.
backup the folder again

step 4.
the file a.txt still exists on the cloud. => BUG

**Comment by extremeshok** [comment]
An option should be added. remove_non_existing_files

If this is enabled files that do not exist on the src will be removed from the dst folder.

Sometimes people need to keep files that have been deleted.

**Comment by ronhanson** [comment]
Is it already solved with the del-non-existing option?

**Comment by frachop** [comment]
yes, since yesterday ;)
